gui:
  border: "single"
  nerdFontsVersion: "3"
  showIcons: true
  showRandomTip: true
  showCommandLog: true
  showBottomLine: true
git:
  pagers:
    - pager: ""
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
os:
  editPreset: 'nvim'
disableStartupPopups: true
customCommands:
  - key: "<c-s>"
    command: 'git diff --cached --quiet || (git commit -m "Sync config: $(date +%Y-%m-%d\ %H:%M:%S)" && git push)'
    context: "files"
    output: popup
